name: Go dev

on:
  push:
    branches: [ feature/* ]
  pull_request:
    branches: [ feature/* ]

env:
  DIRECTORY: src
  TESTS_DIRECTORY: src\tests

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17.8

    - name: Build
      run: go build -v ${{ env.DIRECTORY }}\helloworld.go

    - name: Test
      run: go test -v ./...