name: Go dev

on:
  push:
    branches: [ feature/* ]
  pull_request:
    branches: [ feature/* ]

env:
  DIRECTORY: src
  TESTS_DIRECTORY: src/tests

jobs:

  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ env.DIRECTORY }}
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17.8

    - name: Show github.ref
      env:
        github_ref: ${{ github.ref }}
      run: |
        echo github_ref ${{ github.ref }}
        echo ${github_ref:1}
        echo ${github_ref:2}
        echo ${github_ref:3}

    - name: Build
      run: go build -v

    - name: Test
      run: go test -v ./...