name: Go Release

on:
  release:
    types: [ published ]

env:
  DIRECTORY: src
  PATH_TO_DOCKERFILE: docker/Dockerfile
  DOCKER_NAMESPACE: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_REPOSITORY: go_tasktracker

jobs:
  build:
    name: Build and bush release version of Docker image
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ env.DIRECTORY }}
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17.8

    - name: Build
      run: go build -v

    - name: Test
      run: go test -v ./...

    - name: Set tag environment variable
      id: set_tag
      run: echo ::set-output name=SOURCE_TAG::${GITHUB_REF#refs/tags/}

    - name: Docker login
      run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }} docker.io
    - name: Build docker repo
      run: docker build -f ${{ env.PATH_TO_DOCKERFILE }} -t ${{ env.DOCKER_NAMESPACE }}/${{ env.DOCKER_REPOSITORY }}:${{ steps.set_tag.outputs.SOURCE_TAG }} .
    - name: Push to Docker Hub
      run: docker push ${{ env.DOCKER_NAMESPACE }}/${{ env.DOCKER_REPOSITORY }}:${{ steps.set_tag.outputs.SOURCE_TAG }}
