name: Go dev

on:
  push:
    branches: [ feature/* ]
  pull_request:
    branches: [ feature/* ]

env:
  DIRECTORY: src
  TESTS_DIRECTORY: src/tests

jobs:

  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ env.DIRECTORY }}
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17.8

    - name: Show github.ref
      run: echo github_ref ${{ github.ref }}"

    - name: Build
      run: go build -v

    - name: Test
      run: go test -v ./...